tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'ansible'
brew 'brew-cask'
brew 'tmux'

cask 'antirsi'
cask 'google-chrome-dev'
cask 'iterm2-beta'
cask 'virtualbox'
cask 'firefox-beta-gb'
cask 'harvest'
cask 'macfusion'
cask 'slack'
cask 'vagrant'
